apiVersion: batch/v1
kind: CronJob
metadata:
  name: jenkins-backup
  namespace: jenkins
spec:
  schedule: "0 0 * * *"  # Runs daily at midnight
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: jenkins-backup-sa
          containers:
            - name: backup
              image: alpine:latest
              command:
                - /bin/sh
                - -c
                - |
                  apk update && apk add tar curl unzip
                  curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
                  unzip awscliv2.zip
                  ./aws/install
                  export PATH=$PATH:/usr/local/bin
                  tar -czvf /tmp/jenkins-home-backup.tar.gz /var/jenkins_home
                  aws s3 cp /tmp/jenkins-home-backup.tar.gz s3://jenkins--backups/backups/$(date +\%F)-jenkins-backup.tar.gz
                  rm -rf /tmp/jenkins-home-backup.tar.gz awscliv2.zip ./aws
              volumeMounts:
                - name: jenkins-data
                  mountPath: /var/jenkins_home
          volumes:
            - name: jenkins-data
              persistentVolumeClaim:
                claimName: jenkins-pvc
          restartPolicy: OnFailure

