apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
  labels:
    app: jenkins

spec:
  type: {{ .Values.controller.service.type | quote }}
  ports:
    - port: {{ .Values.controller.service.port }}
      targetPort: 8080
  selector:
    app: jenkins
