apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vprodb-pvc
  labels:
    name: vprodb-pvc
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
