apiVersion: v1
kind: Service
metadata:
  name: vprodb-svc
  labels:
    name: vprodb-svc
spec:
    selector:
      app: vprodb
    ports:
    - name: vprodb-svc-port
      protocol: TCP
      port: 3306
      targetPort: vprodb-port
    type: ClusterIP