apiVersion: apps/v1
kind: Deployment
metadata:
  name: velero
  namespace: velero
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: velero
  template:
    metadata:
      labels:
        app.kubernetes.io/name: velero
    spec:
      serviceAccountName: velero
      initContainers:
        - name: velero-plugin-for-aws
          image: velero/velero-plugin-for-aws:v1.9.2
          volumeMounts:
            - name: plugins
              mountPath: /target
      containers:
        - name: velero
          image: velero/velero:v1.13.2
          args:
            - server
            - --features=EnableCSI
            - --backup-location-config=region=us-east-1,bucket=velero-k8s-backup
            - --snapshot-location-config=region=us-east-1
          volumeMounts:
            - name: plugins
              mountPath: /plugins
            - name: scratch
              mountPath: /scratch
          env:
            - name: VELERO_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: plugins
          emptyDir: {}
        - name: scratch
          emptyDir: {}
